# Generated by Django 5.1.3 on 2024-11-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="todo",
            name="complete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
