# Generated by Django 5.1.2 on 2024-11-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_user_birth_at_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("f", "female"), ("m", "male")],
                max_length=1,
                null=True,
            ),
        ),
    ]
